[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']

# Compiler settings
solc_version = '0.8.19'
optimizer = true
optimizer_runs = 200

# RPC endpoints
[rpc_endpoints]
base_mainnet = "https://mainnet.base.org"
base_testnet = "https://sepolia.base.org"

# Etherscan API keys
[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }

# Gas settings
[gas_limit]
default = 30000000

# Test settings
[fuzz]
runs = 256
max_test_rejects = 65536

